import { Product, Seller, User, Order, Review } from './types'

// Mock Sellers
export const mockSellers: Seller[] = [
  {
    id: 'seller-1',
    userId: 'user-seller-1',
    storeName: 'Sindh Embroidery Collective',
    description: 'Hand-embroidered textiles and clothing from Sindh',
    logo: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=200&h=200&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1000&h=300&fit=crop',
    rating: 4.8,
    totalReviews: 245,
    totalSales: 1250,
    isVerified: true,
    province: 'Sindh',
    specialties: ['Embroidery', 'Textiles', 'Traditional Clothing'],
    responseTime: '2 hours',
    joinDate: new Date('2022-03-15'),
    artisanName: 'Fatima & Sisters Embroidery Circle',
    artisanLocation: 'Hyderabad, Sindh',
    yearsInCraft: 25,
    artisanStory: 'A collective of 15 Sindhi women dedicated to preserving traditional embroidery techniques passed down through generations. Each piece tells a story of cultural heritage and dedication.',
  },
  {
    id: 'seller-2',
    userId: 'user-seller-2',
    storeName: 'Khaddar Dreams',
    description: 'Premium Khaddar fabric clothing and home decor',
    logo: 'https://images.unsplash.com/photo-1487215078519-e21cc028cb29?w=200&h=200&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=1000&h=300&fit=crop',
    rating: 4.6,
    totalReviews: 189,
    totalSales: 890,
    isVerified: true,
    province: 'Sindh',
    specialties: ['Khaddar', 'Home Textiles', 'Casual Wear'],
    responseTime: '1 hour',
    joinDate: new Date('2022-06-20'),
    artisanName: 'Amina & Co. Khaddar Weavers',
    artisanLocation: 'Sukkur, Sindh',
    yearsInCraft: 20,
    artisanStory: 'Dedicated to producing high-quality hand-woven Khaddar fabric using traditional looms, supporting 8 women weavers in the community.',
  },
  {
    id: 'seller-3',
    userId: 'user-seller-3',
    storeName: 'Ajrak Heritage',
    description: 'Traditional Ajrak block-printed textiles and garments',
    logo: 'https://images.unsplash.com/photo-1579033100885-f8852d54b42a?w=200&h=200&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1000&h=300&fit=crop',
    rating: 4.9,
    totalReviews: 312,
    totalSales: 1560,
    isVerified: true,
    province: 'Sindh',
    specialties: ['Ajrak Prints', 'Block Printing', 'Traditional Wear'],
    responseTime: '3 hours',
    joinDate: new Date('2021-11-10'),
    artisanName: 'Rabia Hassan & Family Ajrak Masters',
    artisanLocation: 'Tando Adam, Sindh',
    yearsInCraft: 35,
    artisanStory: 'Master printers continuing a 400-year-old Ajrak tradition. Using natural indigo and vegetable dyes to create authentic block-printed textiles.',
  },
  {
    id: 'seller-4',
    userId: 'user-seller-4',
    storeName: 'Silver & Spice Jewelry',
    description: 'Handcrafted silver jewelry with traditional designs',
    logo: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=200&h=200&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=1000&h=300&fit=crop',
    rating: 4.7,
    totalReviews: 156,
    totalSales: 742,
    isVerified: true,
    province: 'Sindh',
    specialties: ['Silver Jewelry', 'Handcrafted', 'Traditional Designs'],
    responseTime: '4 hours',
    joinDate: new Date('2023-01-05'),
    artisanName: 'Zainab Ali Silver Artisan',
    artisanLocation: 'Karachi, Sindh',
    yearsInCraft: 18,
    artisanStory: 'Specializing in intricate silver jewelry crafted using ancient techniques, supporting women jewelry makers in Karachi.',
  },
  {
    id: 'seller-5',
    userId: 'user-seller-5',
    storeName: 'Sindhi Cuisine Kitchen',
    description: 'Authentic Sindhi food products and spice mixes',
    logo: 'https://images.unsplash.com/photo-1585238341710-4b9932ff448b?w=200&h=200&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1000&h=300&fit=crop',
    rating: 4.8,
    totalReviews: 423,
    totalSales: 2100,
    isVerified: true,
    province: 'Sindh',
    specialties: ['Spice Mixes', 'Food Products', 'Traditional Recipes'],
    responseTime: '1 hour',
    joinDate: new Date('2022-02-14'),
    artisanName: 'Neelam Bibi & Daughters Spice Kitchen',
    artisanLocation: 'Larkana, Sindh',
    yearsInCraft: 30,
    artisanStory: 'Preserving authentic Sindhi recipes with natural spices. Empowering 12 women to process and package traditional food products.',
  },
]

// Mock Products
export const mockProducts: Product[] = [
  {
    id: 'product-1',
    sellerId: 'seller-1',
    sellerName: 'Sindh Embroidery Collective',
    name: 'Hand-Embroidered Sindhi Suit',
    description: 'Beautiful hand-embroidered three-piece Sindhi suit with intricate mirror work and traditional patterns. Made from premium Khaddar fabric.',
    category: 'Clothing',
    images: ['/hand-embroidered-sindhi-suit.png'],
    price: 4500,
    originalPrice: 6000,
    discount: 25,
    rating: 4.9,
    totalReviews: 87,
    inStock: true,
    stockCount: 12,
    tags: ['Handmade', 'Embroidered', 'Sindhi', 'Traditional'],
    createdAt: new Date('2024-01-10'),
    handmade: true,
    certificateOfAuthenticity: 'CERT-2024-001',
  },
  {
    id: 'product-2',
    sellerId: 'seller-1',
    sellerName: 'Sindh Embroidery Collective',
    name: 'Mirror Work Cushion Cover',
    description: 'Vibrant cushion cover with traditional mirror work embroidery. Perfect for adding a cultural touch to your home decor.',
    category: 'Home Decor',
    images: ['/mirror-work-cushion-cover.png'],
    price: 1200,
    originalPrice: 1500,
    discount: 20,
    rating: 4.7,
    totalReviews: 42,
    inStock: true,
    stockCount: 28,
    tags: ['Mirror Work', 'Cushion', 'Home Decor', 'Handmade'],
    createdAt: new Date('2024-01-15'),
    handmade: true,
  },
  {
    id: 'product-3',
    sellerId: 'seller-2',
    sellerName: 'Khaddar Dreams',
    name: 'Premium Khaddar Saree',
    description: 'Elegant hand-woven Khaddar saree with subtle woven patterns. Comfortable and perfect for casual to semi-formal occasions.',
    category: 'Clothing',
    images: ['/premium-khaddar-saree.png'],
    price: 2800,
    originalPrice: 3200,
    discount: 12,
    rating: 4.8,
    totalReviews: 64,
    inStock: true,
    stockCount: 18,
    tags: ['Khaddar', 'Saree', 'Hand-woven', 'Casual Wear'],
    createdAt: new Date('2024-01-12'),
    handmade: true,
  },
  {
    id: 'product-4',
    sellerId: 'seller-3',
    sellerName: 'Ajrak Heritage',
    name: 'Traditional Ajrak Scarf',
    description: 'Authentic Ajrak block-printed scarf featuring traditional geometric patterns. A timeless piece of Sindhi heritage.',
    category: 'Accessories',
    images: ['/traditional-ajrak-scarf.png'],
    price: 1500,
    originalPrice: 2000,
    discount: 25,
    rating: 4.9,
    totalReviews: 156,
    inStock: true,
    stockCount: 35,
    tags: ['Ajrak', 'Block-printed', 'Scarf', 'Traditional'],
    createdAt: new Date('2024-01-08'),
    handmade: true,
  },
  {
    id: 'product-5',
    sellerId: 'seller-3',
    sellerName: 'Ajrak Heritage',
    name: 'Ajrak Printed Dupatta',
    description: 'Beautiful Ajrak dupatta with intricate patterns. Perfect for completing any traditional outfit.',
    category: 'Accessories',
    images: ['/ajrak-printed-dupatta.png'],
    price: 1800,
    rating: 4.6,
    totalReviews: 89,
    inStock: true,
    stockCount: 22,
    tags: ['Ajrak', 'Dupatta', 'Traditional Wear'],
    createdAt: new Date('2024-01-14'),
    handmade: true,
  },
  {
    id: 'product-6',
    sellerId: 'seller-4',
    sellerName: 'Silver & Spice Jewelry',
    name: 'Oxidized Silver Bangles Set',
    description: 'Handcrafted oxidized silver bangles with traditional designs. Set of 6 pieces. Perfect for weddings and special occasions.',
    category: 'Jewelry',
    images: ['/oxidized-silver-bangles-set.png'],
    price: 3200,
    originalPrice: 4000,
    discount: 20,
    rating: 4.8,
    totalReviews: 72,
    inStock: true,
    stockCount: 15,
    tags: ['Silver', 'Bangles', 'Handcrafted', 'Traditional'],
    createdAt: new Date('2024-01-11'),
    handmade: true,
    certificateOfAuthenticity: 'CERT-2024-002',
  },
  {
    id: 'product-7',
    sellerId: 'seller-4',
    sellerName: 'Silver & Spice Jewelry',
    name: 'Silver Filigree Earrings',
    description: 'Delicate silver filigree earrings with intricate traditional patterns. Lightweight and comfortable for daily wear.',
    category: 'Jewelry',
    images: ['/silver-filigree-earrings.png'],
    price: 1400,
    rating: 4.7,
    totalReviews: 45,
    inStock: true,
    stockCount: 20,
    tags: ['Silver', 'Earrings', 'Filigree', 'Handcrafted'],
    createdAt: new Date('2024-01-13'),
    handmade: true,
  },
  {
    id: 'product-8',
    sellerId: 'seller-5',
    sellerName: 'Sindhi Cuisine Kitchen',
    name: 'Authentic Sindhi Spice Mix',
    description: 'Traditional blend of spices used in authentic Sindhi cuisine. Perfect for making traditional dishes at home.',
    category: 'Food & Spices',
    images: ['/authentic-sindhi-spice-mix.png'],
    price: 350,
    originalPrice: 450,
    discount: 22,
    rating: 4.9,
    totalReviews: 234,
    inStock: true,
    stockCount: 100,
    tags: ['Spice Mix', 'Traditional', 'Sindhi', 'Food'],
    createdAt: new Date('2024-01-09'),
    handmade: true,
  },
  {
    id: 'product-9',
    sellerId: 'seller-5',
    sellerName: 'Sindhi Cuisine Kitchen',
    name: 'Dried Sindhi Mangoes',
    description: 'Premium dried mango pieces from Sindh. No added sugar or preservatives. Authentic taste of summer.',
    category: 'Food & Spices',
    images: ['/dried-sindhi-mangoes.png'],
    price: 480,
    originalPrice: 600,
    discount: 20,
    rating: 4.8,
    totalReviews: 178,
    inStock: true,
    stockCount: 50,
    tags: ['Mangoes', 'Dried Fruit', 'Snack', 'Natural'],
    createdAt: new Date('2024-01-16'),
    handmade: true,
  },
  {
    id: 'product-10',
    sellerId: 'seller-2',
    sellerName: 'Khaddar Dreams',
    name: 'Khaddar Bed Sheet Set',
    description: 'Comfortable and durable Khaddar bed sheet set in traditional colors. Perfect for all seasons.',
    category: 'Home Decor',
    images: ['/khaddar-bed-sheet-set.png'],
    price: 2200,
    originalPrice: 2800,
    discount: 21,
    rating: 4.6,
    totalReviews: 95,
    inStock: true,
    stockCount: 25,
    tags: ['Khaddar', 'Bed Sheet', 'Home Decor', 'Comfort'],
    createdAt: new Date('2024-01-17'),
    handmade: true,
    artisanName: 'Amina & Co. Khaddar Weavers',
    artisanLocation: 'Sukkur, Sindh',
    yearsInCraft: 20,
  },
  {
    id: 'product-11',
    sellerId: 'seller-1',
    sellerName: 'Sindh Embroidery Collective',
    name: 'Traditional Sindhi Shawl',
    description: 'Exquisite hand-embroidered Sindhi shawl with intricate mirror work patterns. A versatile piece for any occasion.',
    category: 'Accessories',
    images: ['/traditional-sindhi-shawl.png'],
    price: 3500,
    originalPrice: 5000,
    discount: 30,
    rating: 4.9,
    totalReviews: 112,
    inStock: true,
    stockCount: 10,
    tags: ['Shawl', 'Embroidered', 'Mirror Work', 'Premium'],
    createdAt: new Date('2024-02-01'),
    handmade: true,
    certificateOfAuthenticity: 'CERT-2024-011',
    artisanName: 'Fatima & Sisters Embroidery Circle',
    artisanLocation: 'Hyderabad, Sindh',
    yearsInCraft: 25,
    artisanStory: 'Handcrafted using traditional embroidery techniques passed down through generations of Sindhi women.',
  },
  {
    id: 'product-12',
    sellerId: 'seller-3',
    sellerName: 'Ajrak Heritage',
    name: 'Premium Ajrak Fabric Roll',
    description: '5-meter premium Ajrak fabric suitable for making traditional clothing or home decor. Limited edition natural dye batch.',
    category: 'Textiles',
    images: ['/premium-ajrak-fabric-roll.png'],
    price: 5200,
    originalPrice: 6800,
    discount: 23,
    rating: 4.8,
    totalReviews: 78,
    inStock: true,
    stockCount: 8,
    tags: ['Ajrak', 'Fabric', 'Premium', 'Natural Dye'],
    createdAt: new Date('2024-02-03'),
    handmade: true,
    certificateOfAuthenticity: 'CERT-2024-012',
    artisanName: 'Rabia Hassan & Family Ajrak Masters',
    artisanLocation: 'Tando Adam, Sindh',
    yearsInCraft: 35,
    artisanStory: 'Made using authentic indigo and vegetable dyes, carrying 400 years of Ajrak printing heritage.',
  },
  {
    id: 'product-13',
    sellerId: 'seller-4',
    sellerName: 'Silver & Spice Jewelry',
    name: 'Sindhi Bridal Silver Set',
    description: 'Complete bridal silver jewelry set including necklace, earrings, bangles and anklets. Each piece is uniquely handcrafted.',
    category: 'Jewelry',
    images: ['/sindhi-bridal-silver-set.png'],
    price: 12500,
    originalPrice: 16000,
    discount: 21,
    rating: 4.9,
    totalReviews: 34,
    inStock: true,
    stockCount: 5,
    tags: ['Bridal', 'Silver', 'Jewelry Set', 'Handcrafted', 'Premium'],
    createdAt: new Date('2024-02-05'),
    handmade: true,
    certificateOfAuthenticity: 'CERT-2024-013',
    artisanName: 'Zainab Ali Silver Artisan',
    artisanLocation: 'Karachi, Sindh',
    yearsInCraft: 18,
    artisanStory: 'Each bridal piece is carefully crafted to celebrate Sindhi traditions and the beauty of handmade jewelry.',
  },
  {
    id: 'product-14',
    sellerId: 'seller-5',
    sellerName: 'Sindhi Cuisine Kitchen',
    name: 'Premium Sindhi Pickle Assortment',
    description: 'Set of 3 authentic Sindhi pickles made from natural ingredients and traditional recipes. No preservatives added.',
    category: 'Food & Spices',
    images: ['/premium-sindhi-pickle-assortment.png'],
    price: 850,
    originalPrice: 1200,
    discount: 29,
    rating: 4.7,
    totalReviews: 156,
    inStock: true,
    stockCount: 60,
    tags: ['Pickle', 'Sindhi Food', 'Natural', 'Organic'],
    createdAt: new Date('2024-02-07'),
    handmade: true,
    artisanName: 'Neelam Bibi & Daughters Spice Kitchen',
    artisanLocation: 'Larkana, Sindh',
    yearsInCraft: 30,
    artisanStory: 'Prepared using authentic Sindhi recipes passed through generations, each jar prepared with love and care.',
  },
  {
    id: 'product-15',
    sellerId: 'seller-1',
    sellerName: 'Sindh Embroidery Collective',
    name: 'Hand-Embroidered Table Runner',
    description: 'Beautiful hand-embroidered table runner with traditional Sindhi patterns and mirror work. Adds elegance to any dining space.',
    category: 'Home Decor',
    images: ['/hand-embroidered-table-runner.png'],
    price: 2400,
    originalPrice: 3200,
    discount: 25,
    rating: 4.8,
    totalReviews: 89,
    inStock: true,
    stockCount: 18,
    tags: ['Table Runner', 'Embroidered', 'Home Decor', 'Traditional'],
    createdAt: new Date('2024-02-09'),
    handmade: true,
    artisanName: 'Fatima & Sisters Embroidery Circle',
    artisanLocation: 'Hyderabad, Sindh',
    yearsInCraft: 25,
  },
  {
    id: 'product-16',
    sellerId: 'seller-2',
    sellerName: 'Khaddar Dreams',
    name: 'Premium Khaddar Dress Material',
    description: '2.5 meter Khaddar dress material in premium quality with traditional weave. Perfect for stitching traditional or modern outfits.',
    category: 'Textiles',
    images: ['/premium-khaddar-dress-material.png'],
    price: 1950,
    originalPrice: 2600,
    discount: 25,
    rating: 4.7,
    totalReviews: 67,
    inStock: true,
    stockCount: 30,
    tags: ['Dress Material', 'Khaddar', 'Premium', 'Hand-woven'],
    createdAt: new Date('2024-02-11'),
    handmade: true,
    artisanName: 'Amina & Co. Khaddar Weavers',
    artisanLocation: 'Sukkur, Sindh',
    yearsInCraft: 20,
    artisanStory: 'Woven by skilled women using traditional looms, each piece represents hours of careful craftsmanship.',
  },
]

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'fatima@example.com',
    fullName: 'Fatima Khan',
    phone: '+92 300 1234567',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    address: {
      street: '123 Sindh Road',
      city: 'Karachi',
      province: 'Sindh',
      zipCode: '75000',
      country: 'Pakistan',
    },
    wishlist: ['product-1', 'product-4', 'product-6'],
    createdAt: new Date('2023-06-15'),
    isVerified: true,
  },
]

// Mock Orders
export const mockOrders: Order[] = [
  {
    id: 'order-1',
    userId: 'user-1',
    items: [
      {
        id: 'item-1',
        productId: 'product-1',
        sellerId: 'seller-1',
        sellerName: 'Sindh Embroidery Collective',
        productName: 'Hand-Embroidered Sindhi Suit',
        quantity: 1,
        unitPrice: 4500,
        totalPrice: 4500,
      },
    ],
    totalAmount: 4500,
    status: 'delivered',
    shippingAddress: {
      street: '123 Sindh Road',
      city: 'Karachi',
      province: 'Sindh',
      zipCode: '75000',
      country: 'Pakistan',
    },
    paymentMethod: 'credit_card',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-08'),
    estimatedDelivery: new Date('2024-01-08'),
    trackingNumber: 'TRACK123456',
  },
  {
    id: 'order-2',
    userId: 'user-1',
    items: [
      {
        id: 'item-2',
        productId: 'product-3',
        sellerId: 'seller-2',
        sellerName: 'Khaddar Dreams',
        productName: 'Premium Khaddar Saree',
        quantity: 2,
        unitPrice: 2800,
        totalPrice: 5600,
      },
      {
        id: 'item-3',
        productId: 'product-8',
        sellerId: 'seller-5',
        sellerName: 'Sindhi Cuisine Kitchen',
        productName: 'Authentic Sindhi Spice Mix',
        quantity: 3,
        unitPrice: 350,
        totalPrice: 1050,
      },
    ],
    totalAmount: 6650,
    status: 'shipped',
    shippingAddress: {
      street: '123 Sindh Road',
      city: 'Karachi',
      province: 'Sindh',
      zipCode: '75000',
      country: 'Pakistan',
    },
    paymentMethod: 'debit_card',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
    estimatedDelivery: new Date('2024-01-25'),
    trackingNumber: 'TRACK789012',
  },
]

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: 'review-1',
    productId: 'product-1',
    userId: 'user-1',
    userName: 'Fatima Khan',
    rating: 5,
    title: 'Absolutely Beautiful!',
    comment: 'The embroidery work is exquisite and the quality of the Khaddar is excellent. Wearing it made me feel so connected to Sindhi culture.',
    createdAt: new Date('2024-01-09'),
    helpful: 24,
  },
  {
    id: 'review-2',
    productId: 'product-4',
    userId: 'user-1',
    userName: 'Fatima Khan',
    rating: 5,
    title: 'Authentic and High Quality',
    comment: 'The Ajrak patterns are stunning and the colors are vibrant. This is true heritage wear!',
    createdAt: new Date('2024-01-10'),
    helpful: 18,
  },
]

// Product Categories
export const categories = [
  { id: 'clothing', name: 'Clothing', icon: 'Shirt' },
  { id: 'jewelry', name: 'Jewelry', icon: 'Gem' },
  { id: 'home-decor', name: 'Home Decor', icon: 'Home' },
  { id: 'accessories', name: 'Accessories', icon: 'Briefcase' },
  { id: 'food-spices', name: 'Food & Spices', icon: 'UtensilsCrossed' },
  { id: 'art-culture', name: 'Art & Culture', icon: 'Palette' },
  { id: 'beauty', name: 'Beauty', icon: 'Sparkles' },
  { id: 'handicrafts', name: 'Handicrafts', icon: 'Hammer' },
]
